# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20181225_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='articles.Tag', verbose_name='标签'),
        ),
    ]
