# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-21 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20181225_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_avatar',
            field=models.ImageField(default='article/python.jpg', null=True, upload_to='article/%Y/%m', verbose_name='文章题图'),
        ),
    ]
